name: SST Testing Frameworks Branch CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

#env:
#  SST_CORE_HOME: $HOME/local/sstcore
#  SST_ELEMENTS_HOME: $HOME/local/sstelements

jobs:
  Build_and_Test:
    name: ${{ matrix.TARGET }}/${{ matrix.python }}${{ matrix.other }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
#        python: [2.7, 3.5, 3.6, 3.7, 3.8]
        python: [2.7]
        other: [""]

    steps:
    - name: Checkout SST-Core source
      uses: actions/checkout@v2

    - name: Information Dump 1
      run: |
        echo "*******************************************"
        echo "*** INITIAL INFO DUMP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Set Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET ENV VARIABLES"
        echo "*******************************************"
        echo
        echo "SST_CORE_HOME=$HOME/local/sstcore_install" >> $GITHUB_ENV
        echo "SST_CORE_BIN=$HOME/local/sstcore_install/bin" >> $GITHUB_ENV
        echo "SST_ELEMENTS_HOME=$HOME/local/sstelements_install" >> $GITHUB_ENV
        echo "SST_ELEMENTS_BIN=$HOME/local/sstelements_install/bin" >> $GITHUB_ENV
        echo "$SST_CORE_BIN" >> $GITHUB_PATH
        export PATH=${SST_CORE_BIN}:${PATH}

    - name: Install OpenMPI
      run: |
        echo "*******************************************"
        echo "*** INSTALL OPENMPI"
        echo "*******************************************"
        sudo apt-get install -y openmpi-bin
        echo "***"
        echo "Trying mpirun = " `which mpirun`
        echo "mpirun version = " `mpirun --version`

    - name: Setup Autotools
      run: |
        echo "*******************************************"
        echo "*** INSTALL AUTOTOOLS"
        echo "*******************************************"
#        sudo apt-get install -y autotools-dev
        echo "***"
        export LIBTOOLIZE=$(type -P libtoolize)
        export LIBTOOL=$(type -P "${LIBTOOLIZE%???}")
        echo $LIBTOOLIZE
        echo $LIBTOOL

    - name: Information Dump 2
      run: |
        echo "*******************************************"
        echo "*** BEFORE SST BUILD INFO DUMP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Perform Autogen on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING AUTOGEN ON SST-Core"
        echo "*******************************************"
        ./autogen.sh

    - name: Perform Configure on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING CONFIGURE ON SST-Core"
        echo "*******************************************"
        ./configure --prefix=$SST_CORE_HOME

    - name: Perform Make on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING MAKE ON SST-Core"
        echo "*******************************************"
        make -j16

    - name: Perform Make on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING MAKE INSTALL ON SST-Core"
        echo "*******************************************"
        make install

