name: SST Testing Frameworks Branch CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

#env:
#  SST_CORE_HOME: $HOME/local/sstcore
#  SST_ELEMENTS_HOME: $HOME/local/sstelements

jobs:
  Build_and_Test:
    name: ${{ matrix.TARGET }}/${{ matrix.python }}${{ matrix.other }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
#        python: [2.7, 3.5, 3.6, 3.7, 3.8]
        python: [2.7]
        other: [""]

    steps:
    - name: Checkout SST-Core source
      uses: actions/checkout@v2

    - name: Information Dump 1
      run: |
        echo "*******************************************"
        echo "*** INITIAL INFO DUMP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Set Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET ENV VARIABLES"
        echo "*******************************************"
        echo
        echo "SST_CORE_HOME=$HOME/local/sstcore_install" >> $GITHUB_ENV
        echo "SST_CORE_BIN=$HOME/local/sstcore_install/bin" >> $GITHUB_ENV
        echo "SST_ELEMENTS_HOME=$HOME/local/sstelements_install" >> $GITHUB_ENV
        echo "SST_ELEMENTS_BIN=$HOME/local/sstelements_install/bin" >> $GITHUB_ENV
        echo "***"

    - name: Install OpenMPI
      run: |
        echo "*******************************************"
        echo "*** INSTALL OPENMPI"
        echo "*******************************************"
        sudo apt-get install -y openmpi-bin
        echo "***"
        echo "Trying mpirun = " `which mpirun`
        echo "mpirun version = " `mpirun --version`
        echo "***"

    - name: Setup Autotools
      run: |
        echo "*******************************************"
        echo "*** INSTALL AUTOTOOLS"
        echo "*******************************************"
        echo "Trying to install libtool"
        sudo apt-get install -y libtool-bin
        echo "***"
        export LIBTOOLIZE=$(type -P libtoolize)
        export LIBTOOL=$(type -P "${LIBTOOLIZE%???}")
        echo "LIBTOOLIZE path = " `echo $LIBTOOLIZE`
        echo "LIBTOOL path = " `echo $LIBTOOL`
        echo "LIBTOOLIZE version = " `libtoolize --version`
        echo "ACLOCAL    version = " `aclocal --version`
        echo "AUTOHEADER version = " `autoheader --version`
        echo "AUTOCONF   version = " `autoconf --version`
        echo "AUTOMAKE   version = " `automake --version`
        echo "AUTORECONF version = " `autoreconf --version`
        echo "LIBTOOL    version = " `libtool --version`
        echo "***"

    - name: Information Dump 2
      run: |
        echo "*******************************************"
        echo "*** BEFORE SST BUILD INFO DUMP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Perform Autogen on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING AUTOGEN ON SST-Core"
        echo "*******************************************"
        ./autogen.sh
        echo "***"

    - name: Perform Configure on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING CONFIGURE ON SST-Core"
        echo "*******************************************"
        ./configure --prefix=$SST_CORE_HOME
        echo "***"

    - name: Perform Make on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING MAKE ON SST-Core"
        echo "*******************************************"
        make -j16
        echo "***"

    - name: Perform Install on SST-Core
      run: |
        echo "*******************************************"
        echo "*** RUNNING INSTALL ON SST-Core"
        echo "*******************************************"
        make install

    - name: Check Install of SST-Core
      run: |
        echo "*******************************************"
        echo "*** CHECK INSTALL OF SST-Core"
        echo "*******************************************"
        echo "$HOME path = " `echo $HOME`
        echo "$SST_CORE_HOME path = " `echo $SST_CORE_HOME`
        echo "$SST_CORE_BIN path = " `echo $SST_CORE_BIN`
        echo "ls $HOME "
        ls -lia $HOME
        echo "ls $SST_CORE_HOME"
        ls -lia $SST_CORE_HOME
        echo "ls $SST_CORE_BIN"
        ls -lia $SST_CORE_BIN
        echo "***"
        echo "cd to $HOME"
        cd $HOME
        echo "***"
        echo "sst version = " `$SST_CORE_BIN/sst --version`
        echo "***"
        echo "Trying to PATH to SST BIN DIR"
        echo "$SST_CORE_BIN" >> $GITHUB_PATH
        sst --version

    - name: Perform Testing on SST-Core
      run: |
        echo "*******************************************"
        echo "*** Testing SST-Core"
        echo "*******************************************"
        echo "cd to $HOME"
        cd $HOME
        echo "***"
        $SST_CORE_BIN/sst-test-core
        echo "***"
        echo "ls $HOME "
        ls -lia $HOME
